### ISSUE TITLE
ETL Pipeline Tests

### ISSUE THREAD

**Issue by nicholac** [nismod/infra-risk-vis#122]

**Comment by tomalrussell** [comment]
Suggest closing as this would need fairly heavy integration testing - current approach is to run through a checklist for acceptance:
- run ETL for some/all datasets
- ensure app is running (in dev, staging or prod)
- check data files are in place (TIFFs, MBTiles..)
- check metadata is in place (tile database, `config.json`..)
- visit app in browser
- load layers, check visibility
