### ISSUE TITLE
Separate road asset layers

### ISSUE THREAD

**Issue by tomalrussell** [nismod/infra-risk-vis#16]
Separate road classes into layers

Check vector density of tertiary/unclassified roads - especially roads around Kingston in zoomed-out view. Can tippecanoe show more data here?

**Comment by mz8i** [comment]
Just to confirm: the goal is to also have separate mbtiles for each road class?

**Comment by tomalrussell** [comment]
The goals are:
1. be able to toggle visibility of roads classes separately
2. represent road density and connectivity a bit better, particularly around Kingston. I'd like to see major roads clearly everywhere at all zooms, and get a decent impression of minor roads when zoomed out. 

We might get good-enough results with two separate mbtiles, maybe one for A/B/C, one for METRO/TRACK/OTHER.
