### ISSUE TITLE
Selected feature is not deselected when hiding parent layer

### ISSUE THREAD

**Issue by mz8i** [nismod/infra-risk-vis#24]
When hiding a layer from view, if the selected feature comes from that layer, the selection should be cleared.
Currently, the highlighted selection is still displayed, even though all other features of that layer aren't visible.

Steps to reproduce:
- click on a feature to select
- hide layer to which the feature belongs
- the highlighted feature is still visible

**Comment by mz8i** [comment]
With the new selection highlight implementation (#35), the highlight is no longer shown if the main layer itself is hidden.
However, the feature sidebar for the selected feature is still shown, even if the feature is not visible on the map.
@tomalrussell do we want to do anything about this (e.g. hide the sidebar if the feature is not visible) or is the functionality fine as it is now and we can close this issue?

**Comment by tomalrussell** [comment]
Happy to close this
