### ISSUE TITLE
Search for places to navigate

### ISSUE THREAD

**Issue by tomalrussell** [nismod/infra-risk-vis#27]
Search box to filter on place names, select to zoom to location.

**Comment by mz8i** [comment]
Some requirements analysis:
- when not in use, keep search box collapsed, only show search button
- on button click, expand search box and focus text field
- on user-typed text, search for places with a maximum frequency of 1 request per second (to comply with [Nominatim usage policy](https://operations.osmfoundation.org/policies/nominatim/))
- only search places in Jamaica
- upon receiving list of results:
    - display list of results below search box (interactive, scrollable if long)
    - display results as pins on the map
    - zoom out map to show all pins
- upon hovering over an option in the results list, highlight the pin on the map
- upon selecting (clicking) an option in the results list:
    - zoom to the coordinates of the selected point, at zoom level 12 (or choose optimal zoom level based on data?)
    - hide search result pins from the map
    - collapse search box, but don't clear results (upon re-opening the search box, the search latest query, results and pins should appear again)
