### ISSUE TITLE
Display admin boundaries on map

### ISSUE THREAD

**Issue by mz8i** [nismod/infra-risk-vis#32]
Split out from #26 
Add administrative boundaries layer to map.
Enable toggling boundaries on/off.

**Comment by mz8i** [comment]
@tomalrussell the `admin_boundaries.gpkg` file I have access to contains three levels of administrative divisions (Parish -> Community -> subdivisions of community).

What do you think would be the best way to display this:
- display all boundaries simultaneously (with different line style for each level, toggle on/off)
    - con: the data we have seem to have had a different simplification applied to the two higher divisions (parish and community) vs to the lowest level - so if you overlay all three at the same time, there will be a tangle of lines near some borders
- display the two higher-level divisions simultaneously (toggle on/off at the same time)
   - pro: simplest option
   - con: the lowest division level is not shown at all 
- display just one division level at a time, allow for switching between the three levels or toggling off completely
   - pro: no problem with spatial data discrepancies
   - con: UI potentially too complex compared to how much information this separation gives to the user

Also, do we need to show the names of the administrative boundaries on the map? We could add that to the tile generation step, although currently this might clash with the raster map labels from CARTO.

**Comment by tomalrussell** [comment]
I think we should go for option three - toggle between each division level (one or none active at any time)

For labelling with names, we can try showing them only above a certain zoom level when they are unlikely to overlap.

Future UI direction: we will have some data associated with different admin levels (population, economic activity, aggregated risk results), so there will soon be some use in having a details sidebar appear on click, as for infrastructure assets.
