### ISSUE TITLE
Raster display artefacts and preprocessing

### ISSUE THREAD

**Issue by tomalrussell** [nismod/infra-risk-vis#9]
Seem to come up as darker areas, perhaps around tile joins?

Possibly related - do we already have (or can we test) adding [`terracotta optimize-rasters`](https://terracotta-python.readthedocs.io/en/latest/cli-commands/optimize-rasters.html) to the raster process pipeline?

**Comment by mz8i** [comment]
Following investigation, the artefacts are in the GeoTIFF overviews which are generated as part of the raster pre-processing pipeline. It seems that when using default parameters of `gdal_translate` and the COG driver, the artefacts appear. Need to find the right parameters to set (probably related to raster reprojection/resampling methods)
- see COG driver parameters: https://gdal.org/drivers/raster/cog.html

**Comment by tomalrussell** [comment]
Closed by https://github.com/nismod/infra-risk-vis/commit/ec61d00ade84a4d1e47e6ca838fadef77188fd86
